### PR TITLE
Fixes (#72) : Refactor footer component and import it in Intro component

### PR DESCRIPTION
**Pull request by Venkateeshh**
fixes : #72 
This pull request refactors the Footer component to enhance readability and maintainability, and integrates it into the Intro component, ensuring a consistent user interface across the application. Please review the changes.

## Before 
Screenshot 2024-10-27 222519

## After
Screenshot 2024-10-27 222536

- [x] I have starred and forked the JobSewa repo.
- [x] I have carefully read the instructions for contributing to the project.
- [x] I have created a new page or section and placed it inside the appropriate folder.
- [x] My contributions align with the current project structure and conventions.
- [ ] I have included any necessary images in a dedicated folder within `assets`, ensuring they are compressed and under 500kb.
- [ ] All images are in `.png` format and have been directly uploaded—no external image links are used.
- [x] I understand that the maintainers will review my pull request and provide feedback if necessary.
- [ ] I have assigned a reviewer to this pull request.

### CODE REVIEW

**Comment by Devmangrani** [comment]
Screenshot 2024-10-28 at 12 31 45 PM

Great work on the footer refactor—it's looking fantastic. Could you adjust the alignment on the homepage, though? The increased footer height has shifted the "Find Your Perfect Job with JobSewa" line up towards the navbar, which makes the main content feel a bit cramped. Changing this would really help the layout feel more balanced. I'll share a screenshot to illustrate. Thanks for your efforts!

**Comment by Venkateeshh** [comment]
yea sure will work on it

**Comment by Venkateeshh** [comment]
> Screenshot 2024-10-28 at 12 31 45 PM
> Great work on the footer refactor—it's looking fantastic. Could you adjust the alignment on the homepage, though? The increased footer height has shifted the "Find Your Perfect Job with JobSewa" line up towards the navbar, which makes the main content feel a bit cramped. Changing this would really help the layout feel more balanced. I'll share a screenshot to illustrate. Thanks for your efforts!

fixed the issue

**Comment by Venkateeshh** [comment]
i have fixed the issue mentioned in review

**Comment by Venkateeshh** [comment]
can it be merged?

**Comment by Devmangrani** [comment]
no It is can't able to merge

**Pull request closed without merging**
