### PR TITLE
Navbar Updated with enhanced UI.

### PR DESCRIPTION
**Pull request by Sunscar-Sony**
1- Changed the logo with custom made logo
2- Added elegant on hover animation to the links
3- enhanced the login and sigh up button.

## JobSewa Contribution Checklist ✅

Before submitting a pull request, please ensure that you've followed the guidelines below. This will help expedite the review process. Please remember to follow the [Code of Conduct](../CODE_OF_CONDUCT.md).

**Important**: *Starring the repo shows your support and will ensure your contributions are reviewed in a timely manner.*

- [ ] I have starred and forked the JobSewa repo.
- [ ] I have carefully read the instructions for contributing to the project.
- [ ] I have created a new page or section and placed it inside the appropriate folder.
- [ ] My contributions align with the current project structure and conventions.
- [ ] I have included any necessary images in a dedicated folder within `assets`, ensuring they are compressed and under 500kb.
- [ ] All images are in `.png` format and have been directly uploaded—no external image links are used.
- [ ] I understand that the maintainers will review my pull request and provide feedback if necessary.
- [ ] I have assigned a reviewer to this pull request.

Thank you for your contribution to **JobSewa**! We’re excited to work with you.

### CODE REVIEW

**Comment by Devmangrani** [comment]
You’ve done a fantastic job with these enhancements! The previous logo aligns well with our branding, so I’d love to keep that. I’m really impressed with your “hover animation on links” and the updated “login and sign-up button.” Both changes look amazing! 

Could you please adjust those enhancements to align more closely with our homepage UI? Specifically, I think it would look better if the “hover animation on links” and the “login and sign-up button” design matched the homepage’s aesthetic. Also, The navbar's background color is currently white, but I think it would look great in the previous color. Thank you for these wonderful contributions!

**Comment by Sunscar-Sony** [comment]
Thank you for your feedback! I’ll update the logo to the previous design as requested. I’d also love to work on the homepage UI to ensure everything aligns with the overall theme and enhances the website’s look, including the footer section. If you allow me to proceed with these updates, I’ll do my best to make everything cohesive and visually appealing.

Looking forward to your approval!

**Comment by Devmangrani** [comment]
Thank you for your willingness to make these updates, @Sunscar-Sony  Absolutely, please go ahead with the improvements. I’m excited to see the cohesive design and how it enhances the overall look of the website. Appreciate your dedication to making everything align smoothly!

**Comment by Devmangrani** [comment]
@Sunscar-Sony 
Bro I really love the UI
You’ve truly transformed the homepage UI—it looks fantastic! I absolutely love the updates; they make the interface so cool and visually appealing. Just one small request—could we try swapping the homepage photo for one that aligns more closely with our purpose, similar to the previous one?

Thank you so much for your hard work and attention to detail. You’ve really elevated our design!

**Pull request merged**
