### PR TITLE
NGOs added

### PR DESCRIPTION
**Pull request by saumy-sh**
Issue solve #102 
## JobSewa Contribution Checklist ✅

Before submitting a pull request, please ensure that you've followed the guidelines below. This will help expedite the review process. Please remember to follow the [Code of Conduct](../CODE_OF_CONDUCT.md).

**Important**: *Starring the repo shows your support and will ensure your contributions are reviewed in a timely manner.*

- [x] I have starred and forked the JobSewa repo.
- [x] I have carefully read the instructions for contributing to the project.
- [x] I have created a new page or section and placed it inside the appropriate folder.
- [x] My contributions align with the current project structure and conventions.
- [x] I have included any necessary images in a dedicated folder within `assets`, ensuring they are compressed and under 500kb.
- [x] All images are in `.png` format and have been directly uploaded—no external image links are used.
- [x] I understand that the maintainers will review my pull request and provide feedback if necessary.
- [x] I have assigned a reviewer to this pull request.

Thank you for your contribution to **JobSewa**! We’re excited to work with you.

### CODE REVIEW

**Comment by Devmangrani** [comment]
Good work, bro, and Happy Diwali! 🎉 I've merged your PR, but I noticed a couple of issues: it seems some of the new NGOs might not have images, or they’re not showing up properly on the organization's page. Let’s take a look at that to make sure everything displays as expected. Thanks for your contributions!

You can update your PR whenever you're free to attach images for the NGOs and make them look consistent with the others; otherwise, I'll need to revert your merges. Let me know if you need any help with this. Thanks!

**Comment by saumy-sh** [comment]
Yes that's because you will have to put photos in your cloudinary account where you have put other icons.

Also a very happy diwali to you too!🪔☺️
Thanks for merging the PR

**Comment by Devmangrani** [comment]
I appreciate your contributions to the project.
Could you provide me with the pictures for the new NGOs? That way, I can upload them to Cloudinary and ensure they display correctly on the organization page.

**Comment by saumy-sh** [comment]
Here are pictures of NGOs with their names. Some don't have a logo image.
hand in hand
kvic
labournet
def
give india

**Comment by saumy-sh** [comment]
Here are some more logos
skill india
youth4jobs

**Pull request merged**
