### PR TITLE
Update NavBar.jsx

### PR DESCRIPTION
**Pull request by KhanjarSingh**
Now if you press the Job sewa button it redirects you to home
This fixes the issue #9

### CODE REVIEW

**Comment by Devmangrani** [comment]
Screenshot 2024-10-21 at 6 28 00 PM
@KhanjarSingh when i am clicking the jobsewa logo button it redirect me to this "404
This page could not be found." Page

**Comment by Devmangrani** [comment]
It looks like the issue is with the link in the `<Link>` component. Instead of `"/frontend"`, you should put the home page link. It should look something like this:

```jsx
<Link
  href={"/"} // Update this to the home page link
  className="px-3 mx-4 text-base font-medium transition-all duration-700 hover:translate-y-2 uppercase"
>
  𝓙ob𝓢𝓮𝔀𝓪
</Link>
```

This will redirect you to the home page correctly. Let me know if you need further assistance!

**Comment by KhanjarSingh** [comment]
@Devmangrani is it ok ? like i have tried

**Comment by Devmangrani** [comment]
You’ve done good work, @KhanjarSingh! Keep it up!

**Pull request merged**
