### PR TITLE
[FEATURE]:Added mail notification system and NGOs

### PR DESCRIPTION
**Pull request by saumy-sh**
Issue solved #86 
## Setup for enabling feature
I have used **MailTrap** for mailing purposes. You will have to setup your mailtrap account(free trial available), in order to get your mail id and API access token. Once you get these required things, you have to **update these details in .env file**. Now you are ready to go!

## Demo Video of feature working

https://github.com/user-attachments/assets/36857c59-c0b1-495a-8c14-2edf9872fcbf

## JobSewa Contribution Checklist ✅

Before submitting a pull request, please ensure that you've followed the guidelines below. This will help expedite the review process. Please remember to follow the [Code of Conduct](../CODE_OF_CONDUCT.md).

**Important**: *Starring the repo shows your support and will ensure your contributions are reviewed in a timely manner.*

- [x] I have starred and forked the JobSewa repo.
- [x] I have carefully read the instructions for contributing to the project.
- [x] I have created a new page or section and placed it inside the appropriate folder.
- [x] My contributions align with the current project structure and conventions.
- [x] I have included any necessary images in a dedicated folder within `assets`, ensuring they are compressed and under 500kb.
- [x] All images are in `.png` format and have been directly uploaded—no external image links are used.
- [x] I understand that the maintainers will review my pull request and provide feedback if necessary.
- [x] I have assigned a reviewer to this pull request.

Thank you for your contribution to **JobSewa**! We’re excited to work with you.

### CODE REVIEW

**Comment by Devmangrani** [comment]
Great work, @saumy-sh  I’ll set up the MailTrap account and add the API token to the .env file later. Thanks for the detailed instructions!

**Comment by saumy-sh** [comment]
Once the feature works then can you merge the issue, as hacktoberfest deadline is tomorrow.

**Comment by Devmangrani** [comment]
yes , Sure bro

**Comment by saumy-sh** [comment]
What's the problem you are encountering? I think this issue can be solved.

**Comment by saumy-sh** [comment]
Also the dark mode issue has already been assigned.

**Comment by saumy-sh** [comment]
Just check if you have installed mailttap or not. If not then run command 
```
npm install mailtrap
```
After setting your account in mailtrap you can go to sending domains section on the left side, and get your domain. Remember to select API, there you can see host and API token, these are the two details you need to put in .env file.

I am attaching a photo of my screen, how it looks like.

**Comment by saumy-sh** [comment]
Do this and let me know if it works for you.

**Comment by saumy-sh** [comment]
The code works, it's just that you have to setup mailtrap correctly. So you can merge the request for time being and we can work this out later, as hacktoberfest is about to end.

**Comment by Devmangrani** [comment]
I’ve tried setting up everything with MailTrap, but the issue arises when adding the domain—I’m unable to complete that step. If you're still looking to contribute to Hacktoberfest from this project, I have an idea: you could add more NGOs to the organization page using the same card component—it’s a straightforward task that would be helpful! 
As for dark mode, no one is actively working on it, even though it’s assigned. You could try implementing it if you're up for it. Let me know how you’d like to proceed!

**Comment by saumy-sh** [comment]
Sure I can do the dark mode, can you assign it to me?

**Comment by Devmangrani** [comment]
Yes, please go ahead and open an issue for it! Thank you for contributing!

**Comment by saumy-sh** [comment]
I have opened the issue. Can you quickly assign it to me so that I can complete it fast?

**Comment by Devmangrani** [comment]
I’ve assigned the issue to you! If you have any questions or need support with Hacktoberfest or contributions, feel free to reach out. Good luck, and thanks again for your work!

**Comment by saumy-sh** [comment]
Do I have to delete previous fork to create new one for contribution?

**Comment by Devmangrani** [comment]
No, you can continue working in the same fork for your contributions.

**Comment by saumy-sh** [comment]
> No, you can continue working in the same fork for your contributions.

Then notification change will also be there. Is it fine?

**Comment by Devmangrani** [comment]
Yes, that's perfectly fine. The notification changes will still be there in your fork, and you can continue contributing with the same setup.

**Comment by saumy-sh** [comment]
Okay, can you specify the file where I can add new organizations?

**Comment by Devmangrani** [comment]
I've reviewed the new organizations you've added—great work! However, I can't merge this PR since merging it would also include the mail notification system, which currently has some issues on my end.

To create a new PR:

1. **Create a New Branch:** From your forked repository, create a new branch for the NGOs addition.
2. **Copy the Changes:** Copy the changes related to the NGO additions from your current branch to this new branch.
3. **Commit and Push:** Commit your changes and push the new branch to your fork.
4. **Open a New PR:** Go to the main repository, select "New Pull Request," and choose your new branch with only the NGO changes.

This will help keep each feature separated. Let me know if you need any help with this!

**Comment by saumy-sh** [comment]
But when I am making new branch those changes are still showing. How can I remove notification changes and add NGOs change only. Please help as I haven't done this before

**Comment by Devmangrani** [comment]
To separate the changes for NGOs from the notification feature, follow these steps:

1. **Create a New Branch from the Main Repository's Latest Code**:
   - Go to your forked repository on GitHub.
   - Switch to the main branch and make sure it’s up to date with the latest code from the main repository.
   - Create a new branch from this up-to-date main branch. You can name it something like `add-ngos-only`.

2. **Copy Only the NGO Changes**:
   - Open the file(s) where you made changes for the NGOs in the original branch.
   - Copy the relevant code or data for the NGOs addition.

3. **Paste and Commit in the New Branch**:
   - Go to your new branch `add-ngos-only`.
   - Paste in only the NGO changes, making sure no mail notification code is included.
   - Commit these changes with a descriptive message like "Added new NGOs".

4. **Push and Create the New PR**:
   - Push the `add-ngos-only` branch to your forked repository.
   - Go to the main repository, click on "New Pull Request," and select your new branch for the NGO changes.

Let me know if you need any further help with this process!

**Pull request merged**
